//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compilador.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compilador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// General Information about an assembly is controlled through the following
        ///// set of attributes. Change these attribute values to modify the information
        ///// associated with an assembly.
        ///[assembly: AssemblyTitle(&quot;TreeApp&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;&quot;)]
        ///[assembly: AssemblyProduct(&quot;TreeApp&quot;)]
        ///[assembly: AssemblyCopyright [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AssemblyInfo {
            get {
                return ResourceManager.GetString("AssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// General Information about an assembly is controlled through the following 
        ///// set of attributes. Change these attribute values to modify the information
        ///// associated with an assembly.
        ///[assembly: AssemblyTitle(&quot;WindowsGame1&quot;)]
        ///[assembly: AssemblyProduct(&quot;WindowsGame1&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;&quot;)]
        ///[assembly: AssemblyCopyright(&quot;Copyright ©  2021&quot;)]
        ///[ass [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AssemblyInfo1 {
            get {
                return ResourceManager.GetString("AssemblyInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Beep {
            get {
                object obj = ResourceManager.GetObject("Beep", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap car1 {
            get {
                object obj = ResourceManager.GetObject("car1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap car2 {
            get {
                object obj = ResourceManager.GetObject("car2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap car3 {
            get {
                object obj = ResourceManager.GetObject("car3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap car4 {
            get {
                object obj = ResourceManager.GetObject("car4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dot {
            get {
                object obj = ResourceManager.GetObject("dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dot1 {
            get {
                object obj = ResourceManager.GetObject("dot1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Draw4 {
            get {
                object obj = ResourceManager.GetObject("Draw4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Draw5 {
            get {
                object obj = ResourceManager.GetObject("Draw5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Ejercicios {
            get {
                object obj = ResourceManager.GetObject("Ejercicios", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200	Ha escrito un símbolo inicial no válido (como punto, raya baja, etc.).  Póngalo en el contexto correcto, o elimínelo.
        ///205	Ha escrito una comilla simple seguida por otra.  Debe insertar otro símbolo entre ambas comillas.
        ///212	Empezó a escribir un número decimal, pero no lo completó.  Elimine el punto o termínele con un dígito.
        ///213	Abrió una comilla simple.  Debe existir exactamente un carácter y otra comilla simple después de la primera.
        ///214	Empezó a escribir un número decimal (positivo o negativo), p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200	Ha escrito un símbolo inicial no válido (como punto, raya baja, etc.).  Póngalo en el contexto correcto, o elimínelo.
        ///205	Ha escrito una comilla simple seguida por otra.  Debe insertar otro símbolo entre ambas comillas.
        ///212	Empezó a escribir un número decimal, pero no lo completó.  Elimine el punto o termínele con un dígito.
        ///213	Abrió una comilla simple.  Debe existir exactamente un carácter y otra comilla simple después de la primera.
        ///214	Empezó a escribir un número decimal (positivo o negativo), p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Errors1 {
            get {
                return ResourceManager.GetString("Errors1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EstadosTransición {
            get {
                object obj = ResourceManager.GetObject("EstadosTransición", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fibonacci {
            get {
                object obj = ResourceManager.GetObject("Fibonacci", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Drawing;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Windows.Forms;
        ///using System.Runtime.InteropServices;
        ///
        ///namespace TreeApp
        ///{
        ///    public partial class Form1 : Form
        ///    {
        ///
        ///	[DllImport(&quot;kernel32.dll&quot;, SetLastError = true)]
        ///        [return: MarshalAs(UnmanagedType.Bool)]
        ///        static extern bool AllocConsole();
        ///
        ///        public Form1()
        ///        {
        ///            InitializeCompon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Drawing;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Windows.Forms;
        ///using System.Runtime.InteropServices;
        ///
        ///namespace TreeApp
        ///{
        ///    public partial class Form1 : Form
        ///    {
        ///
        ///	[DllImport(&quot;kernel32.dll&quot;, SetLastError = true)]
        ///        [return: MarshalAs(UnmanagedType.Bool)]
        ///        static extern bool AllocConsole();
        ///
        ///        public Form1()
        ///        {
        ///            InitializeCompon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Form1___Copy {
            get {
                return ResourceManager.GetString("Form1___Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Form1_2021_08_06_02_59_30 {
            get {
                return ResourceManager.GetString("Form1_2021_08_06_02_59_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace TreeApp
        ///{
        ///    partial class Form1
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Required designer variable.
        ///        /// &lt;/summary&gt;
        ///        private System.ComponentModel.IContainer components = null;
        ///
        ///        /// &lt;summary&gt;
        ///        /// Clean up any resources being used.
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;disposing&quot;&gt;true if managed resources should be disposed; otherwise, false.&lt;/param&gt;
        ///        protected override void Dispose(bool disposing)
        ///        {
        ///            if (disposing [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Form1_Designer {
            get {
                return ResourceManager.GetString("Form1_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Form11 {
            get {
                return ResourceManager.GetString("Form11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FuncionPartes {
            get {
                object obj = ResourceManager.GetObject("FuncionPartes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Game {
            get {
                object obj = ResourceManager.GetObject("Game", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.Xna.Framework;
        ///using Microsoft.Xna.Framework.Audio;
        ///using Microsoft.Xna.Framework.Content;
        ///using Microsoft.Xna.Framework.GamerServices;
        ///using Microsoft.Xna.Framework.Graphics;
        ///using Microsoft.Xna.Framework.Input;
        ///using Microsoft.Xna.Framework.Media;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ////// &lt;summary&gt;
        ///    /// This is the main type for your game
        ///    /// &lt;/summary&gt;
        ///    public class Game1 : Microsoft.Xna.Framework.Game
        ///    {
        ///        GraphicsDeviceMan [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Game1 {
            get {
                return ResourceManager.GetString("Game1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.Xna.Framework;
        ///using Microsoft.Xna.Framework.Audio;
        ///using Microsoft.Xna.Framework.Content;
        ///using Microsoft.Xna.Framework.GamerServices;
        ///using Microsoft.Xna.Framework.Graphics;
        ///using Microsoft.Xna.Framework.Input;
        ///using Microsoft.Xna.Framework.Media;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///
        ////// &lt;summary&gt;
        ////// This is the main type for your game
        ////// &lt;/summary&gt;
        ///public class Game1 : Microsoft.Xna.Framework.Game
        ///    {
        ///        GraphicsDeviceManager graph [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Game1___Copy {
            get {
                return ResourceManager.GetString("Game1___Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.Xna.Framework;
        ///using Microsoft.Xna.Framework.Audio;
        ///using Microsoft.Xna.Framework.Content;
        ///using Microsoft.Xna.Framework.GamerServices;
        ///using Microsoft.Xna.Framework.Graphics;
        ///using Microsoft.Xna.Framework.Input;
        ///using Microsoft.Xna.Framework.Media;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ////// &lt;summary&gt;
        ///    /// This is the main type for your game
        ///    /// &lt;/summary&gt;
        ///    public class Game1 : Microsoft.Xna.Framework.Game
        ///    {
        ///public static Random rand [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Game11 {
            get {
                return ResourceManager.GetString("Game11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Game2 {
            get {
                object obj = ResourceManager.GetObject("Game2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GameThumbnail {
            get {
                object obj = ResourceManager.GetObject("GameThumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GameThumbnail1 {
            get {
                object obj = ResourceManager.GetObject("GameThumbnail1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entero,e
        ///ent,e
        ///decimal,b
        ///dec,b
        ///carácter,g
        ///car,g
        ///texto,t
        ///tex,t
        ///lógico,h
        ///log,h
        ///verdad,v
        ///falso,q
        ///textura,r
        ///ras,r
        ///col,k
        ///color,k
        ///si,u
        ///sinosi,w
        ///sino,x
        ///seleccion,y
        ///caso,z
        ///predeterminado,á
        ///fin,f
        ///mientras,é
        ///hacer,í
        ///repetir,ñ
        ///para,ó
        ///salir,s
        ///nada,ë
        ///retornar,°
        ///dibujar,ö
        ///negro,l
        ///azul,l
        ///verde,l
        ///celeste,l
        ///rojo,l
        ///rosado,l
        ///amarillo,l
        ///blanco,l
        ///pi,l
        ///probar,ú
        ///error,ü
        ///funcion,{
        ///sen,10
        ///cos,11
        ///tan,12
        ///potencia,13
        ///esperar,14
        ///raízcuadrada,15
        ///leer,16
        ///escribir,17
        ///convertir,18
        ///reprodu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {,i,(,),~,},ö,e,b,t,g,h,r,k,ë,c,f,s,[,],=,a,d,%,v,q,+,-,*,/,^,l,¿,#,m,&gt;,¡,&lt;,&amp;,o,u,w,x,y,z,á,é,í,ñ,ó,p,°,ú,ü,$
        ///s6,s22,-1,-1,-1,-1,-1,s31,s32,s33,s34,s35,s36,s37,s38,-1,-1,s18,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,s23,-1,-1,s24,-1,-1,s25,s26,s27,s28,-1,s29,s30,-1,-1
        ///-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,acc
        ///-3,s22,-3,-3,-3,-3,-3,s31,s32,s33,s34,s35,s36,s37, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LALR1 {
            get {
                return ResourceManager.GetString("LALR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&apos;,P,F,M,D,T,B,É,S,I,G,L,U,A,C,K,Q,X,E,J,N,R,O,Í,Ñ,Ó,Ú,V,W,H,Y,Z,Ä,Ë,Ö,\,_,`,Á,Ï
        ///,1,2,4,,21,,,3,5,7,,,8,9,,,,,,,,,10,,11,,,12,13,14,15,,,,16,17,19,,20
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,21,,,39,5,7,,,8,9,,,,,,,,,10,,11,,,12,13,14,15,,,,16,17,19,,20
        ///,,,,40,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,42,4,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,44,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LALR2 {
            get {
                return ResourceManager.GetString("LALR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i,1
        ///+,0
        ///-,0
        ///*,0
        ////,0
        ///^,0
        ///&amp;,0
        ///o,0
        ///&lt;,0
        ///¡,0
        ///=,0
        ///¿,0
        ///&gt;,0
        ///m,0
        ///#,0
        ///%,0
        ///a,0
        ///d,0
        ///[,0
        ///],0
        ///p,0
        ///c,0
        ///~,0
        ///(,0
        ///),0
        ///l,1
        ///l,1
        ///l,1
        ///l,1
        ///},0.
        /// </summary>
        public static string Lexemes {
            get {
                return ResourceManager.GetString("Lexemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Manual_1___Conociendo_el_Editor {
            get {
                object obj = ResourceManager.GetObject("Manual_1___Conociendo_el_Editor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Manual_2___Conociendo_el_lenguaje {
            get {
                object obj = ResourceManager.GetObject("Manual_2___Conociendo_el_lenguaje", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_Xna_Framework {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Xna_Framework", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_Xna_Framework_Game {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Xna_Framework_Game", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_Xna_Framework_GamerServices {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Xna_Framework_GamerServices", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_Xna_Framework_Graphics {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Xna_Framework_Graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_Xna_Framework_Input_Touch {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Xna_Framework_Input_Touch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string options1 {
            get {
                return ResourceManager.GetString("options1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Windows.Forms;
        ///
        ///namespace TreeApp
        ///{
        ///    static class Program
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// The main entry point for the application.
        ///        /// &lt;/summary&gt;
        ///        [STAThread]
        ///        static void Main()
        ///        {
        ///            Application.EnableVisualStyles();
        ///            Application.SetCompatibleTextRenderingDefault(false);
        ///            Application.Run(new Form1());
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Runtime.InteropServices;
        ///
        ///static class Program
        ///    {
        ///
        ///    
        ///    /// &lt;summary&gt;
        ///    /// The main entry point for the application.
        ///    /// &lt;/summary&gt;
        ///    [STAThread]
        ///        static void Main(string[] args)
        ///        {
        ///
        ///        using (Game1 game = new Game1())
        ///            {
        ///                game.Run();
        ///            }
        ///
        ///        }
        ///}
        ///
        ///.
        /// </summary>
        public static string Program1 {
            get {
                return ResourceManager.GetString("Program1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Program2 {
            get {
                object obj = ResourceManager.GetObject("Program2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetResources()
        {
            return ResourceManager.GetString("Resources", resourceCulture);
        }

        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.42000
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///
        ///namespace TreeApp.Properties
        ///{
        ///    /// &lt;summary&gt;
        ///    ///   A strongly-typed resource class, for look [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Resources_Designer {
            get {
                return ResourceManager.GetString("Resources_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string respuesta {
            get {
                return ResourceManager.GetString("respuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&apos;,P
        ///P,F S D
        ///P,F S
        ///P,S D
        ///P,S
        ///F,M F
        ///F,M
        ///M,{ T i ( B ) ~ } S
        ///D,ö ~ } S
        ///T,e
        ///T,b
        ///T,t
        ///T,g
        ///T,h
        ///T,r
        ///T,k
        ///T,ë
        ///B,É c B
        ///B,É
        ///É,T i
        ///S,I } S
        ///S,I } f
        ///I,G
        ///I,A
        ///I,C
        ///I,Í
        ///I,Ó
        ///I,W
        ///I,H
        ///I,Y
        ///I,Z
        ///I,\
        ///I,_
        ///I,s
        ///I,`
        ///G,T L
        ///G,T i [ Á ]
        ///L,U c L
        ///L,U
        ///U,i
        ///U,A
        ///A,i = E
        ///A,i = K
        ///C,i a
        ///C,i d
        ///K,Q O K
        ///K,( Q O K )
        ///K,Q
        ///Q,X
        ///Q,% X
        ///X,E R E
        ///X,v
        ///X,q
        ///E,E + J
        ///E,E - J
        ///E,J
        ///J,J * N
        ///J,J / N
        ///J,J ^ N
        ///J,N
        ///N,i
        ///N,i [ Á ]
        ///N,( E )
        ///N,l
        ///N,`
        ///R,¿
        ///R,#
        ///R,m
        ///R,&gt;
        ///R,¡
        ///R,&lt;
        ///O,&amp;
        ///O,o
        ///Í,u ( K ) ~ } S Ñ
        ///Í,u ( K [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;SettingsFile xmlns=&quot;http://schemas.microsoft.com/VisualStudio/2004/01/settings&quot; CurrentProfile=&quot;(Default)&quot;&gt;
        ///  &lt;Profiles&gt;
        ///    &lt;Profile Name=&quot;(Default)&quot; /&gt;
        ///  &lt;/Profiles&gt;
        ///  &lt;Settings /&gt;
        ///&lt;/SettingsFile&gt;
        ///.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.42000
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///
        ///namespace TreeApp.Properties
        ///{
        ///    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribut [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Settings_Designer {
            get {
                return ResourceManager.GetString("Settings_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Sort {
            get {
                object obj = ResourceManager.GetObject("Sort", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hola.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] test1 {
            get {
                object obj = ResourceManager.GetObject("test1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap test2 {
            get {
                object obj = ResourceManager.GetObject("test2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap test21 {
            get {
                object obj = ResourceManager.GetObject("test21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TreeApp {
            get {
                object obj = ResourceManager.GetObject("TreeApp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;15.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProjectGuid&gt;{CD06C358 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TreeApp1 {
            get {
                return ResourceManager.GetString("TreeApp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TreeApp2 {
            get {
                object obj = ResourceManager.GetObject("TreeApp2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TreeApp3 {
            get {
                object obj = ResourceManager.GetObject("TreeApp3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Voto {
            get {
                object obj = ResourceManager.GetObject("Voto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WindowsGame1 {
            get {
                object obj = ResourceManager.GetObject("WindowsGame1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WindowsGame1_csproj_Debug {
            get {
                object obj = ResourceManager.GetObject("WindowsGame1_csproj_Debug", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project DefaultTargets=&quot;Build&quot; ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;ProjectGuid&gt;{81FE03C6-9C6C-4639-B9A1-42F0B171F15B}&lt;/ProjectGuid&gt;
        ///    &lt;ProjectTypeGuids&gt;{6D335F3A-9D43-41b4-9D22-F6F17C4BE596};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&lt;/ProjectTypeGuids&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;x86&lt;/Platform&gt;
        ///    &lt;OutputType&gt;Exe&lt;/OutputType&gt;
        ///    &lt;AppDe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WindowsGame11 {
            get {
                return ResourceManager.GetString("WindowsGame11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WindowsGame12 {
            get {
                object obj = ResourceManager.GetObject("WindowsGame12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WindowsGame13 {
            get {
                object obj = ResourceManager.GetObject("WindowsGame13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WindowsGame14 {
            get {
                object obj = ResourceManager.GetObject("WindowsGame14", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WindowsGame1Content {
            get {
                object obj = ResourceManager.GetObject("WindowsGame1Content", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WindowsGame1Content__2_ {
            get {
                object obj = ResourceManager.GetObject("WindowsGame1Content__2_", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
